### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Kayden89** [Topstar88/Salon-Booking#3]
Hi @Topstar88 , Thanks for sharing such a great code for salon-booking.
I`d like to know how to install this script on my laptop locally and run it.
Regards.

**Comment by Topstar88** [comment]
I used Codeigniter to build this script. 
Please just follow this link and let me know if this would be the answer to your question.
https://codeigniter.com/userguide3/installation/index.html
Regards

**Comment by Kayden89** [comment]
Thank you.
