### ISSUE TITLE
Is it only for salon booking

### ISSUE THREAD

**Issue by ugintl** [Topstar88/Salon-Booking#4]
Is it only for salon booking or it can be used for any type of booking service? 

Just a general question. Is appointment and booking same thing?

**Comment by Topstar88** [comment]
This script surely can be used for other booking types.

**Comment by ugintl** [comment]
@Topstar88 When I go to /install page, it says `404 not found`

**Comment by EmRcc64** [comment]
> @Topstar88 When I go to /install page, it says `404 not found`

Same here, i tried it on a subdomain and after any login i get "ERR_FAIL", any ideas?
