### ISSUE TITLE
Installation Steps

### ISSUE THREAD

**Issue by yvan946** [Topstar88/Salon-Booking#8]
Hi,

I dont have the file install in the repository, the installation have changed?

**Comment by yvan946** [comment]
And do you have the table for the database?

**Comment by Topstar88** [comment]
Hi @yvan946 . If you are using xampp for the local testing, you can copy the source code into public_html. 
Then execute this URL to start the installation. 
http://localhost/install
All the tables will be created automatically once you pass all the installation steps. 
Before that, you create an empty db table in phpmyadmin.

**Comment by yvan946** [comment]
Hi,

Thank you a lot for your help, all is working. I just need to specify the port of my server in the configuration: localhost:3306.
